[2024-09-06 03:44:31,903] [INFO] [root::train_net::127] Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   51
        Validation size: 5
        Checkpoints:     True
        Device:          cpu
        Images scaling:  0.5
        Mixed Precision: False
/app/model.py:142: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  grad_scaler = torch.cuda.amp.GradScaler(enabled=amp)
Epoch 1/5:   0%|          | 0/51 [00:00<?, ?img/s]/app/model.py:163: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
Epoch 1/5:  10%|▉         | 5/51 [00:05<00:22,  2.02img/s, loss (batch)=1.21]
Validation round:   0%|          | 0/5 [00:00<?, ?batch/s]
[2024-09-06 03:44:42,013] [INFO] [root::train_net::198] Validation Dice score: 3.3840172886101527e-09

[2024-09-06 03:44:42,167] [DEBUG] [urllib3.connectionpool::_new_conn::1051] Starting new HTTPS connection (1): api.wandb.ai:443
[2024-09-06 03:44:43,050] [DEBUG] [urllib3.connectionpool::_make_request::546] https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 None
Epoch 1/5:  10%|▉         | 5/51 [00:05<00:22,  2.02img/s, loss (b/app/model.py:163: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
Epoch 1/5:  20%|█▉        | 10/51 [00:12<00:26,  1.53img/s, loss (batch)=0.924]
Validation round:   0%|          | 0/5 [00:00<?, ?batch/s]
[2024-09-06 03:44:49,069] [INFO] [root::train_net::198] Validation Dice score: 3.3840172886101527e-09

Validation round:  20%|██        | 1/5 [00:04<00:17,  4.46s/batch]


Validation round:   0%|          | 0/5 [00:00<?, ?batch/s]
Epoch 1/5:  59%|█████▉    | 30/51 [00:34<00:11,  1.79img/s, loss (batch)=0.704]

Validation round:   0%|          | 0/5 [00:00<?, ?batch/s]
Epoch 1/5:  69%|██████▊   | 35/51 [00:40<00:08,  1.78img/s, loss (batch)=0.7]

Validation round:   0%|          | 0/5 [00:00<?, ?batch/s]
[2024-09-06 03:45:17,579] [INFO] [root::train_net::198] Validation Dice score: 0.05122149735689163
Validation round:   0%|          | 0/5 [00:00<?, ?batch/s]
[2024-09-06 03:45:23,280] [INFO] [root::train_net::198] Validation Dice score: 0.5043207406997681
[2024-09-06 03:45:28,935] [INFO] [root::train_net::198] Validation Dice score: 0.7670576572418213
[2024-09-06 03:45:29,998] [DEBUG] [urllib3.connectionpool::_new_conn::1051] Starting new HTTPS connection (1): o151352.ingest.sentry.io:443


Validation round:  20%|██        | 1/5 [00:04<00:17,  4.44s/batch]
[2024-09-06 03:45:34,615] [INFO] [root::train_net::198] Validation Dice score: 0.8527532815933228
[2024-09-06 03:45:35,024] [ERROR] [label_studio_ml.api::log_exception::1414] Exception on /webhook [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/label_studio_ml/api.py", line 126, in webhook
    model.fit(event, data)
  File "/app/model.py", line 429, in fit
    train_net(images,masks,net,device)
  File "/app/model.py", line 213, in train_net
    Path(dir_checkpoint).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-09-06 03:45:35,026] [DEBUG] [label_studio_ml.api::log_response_info::185] Response status: 500 INTERNAL SERVER ERROR
[2024-09-06 03:45:35,026] [DEBUG] [label_studio_ml.api::log_response_info::186] Response headers: Content-Type: text/html; charset=utf-8
Content-Length: 265
