2024-09-06 02:31:16,998 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Current SDK version is 0.17.9
2024-09-06 02:31:16,998 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Configure stats pid to 34
2024-09-06 02:31:16,998 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Loading settings from /root/.config/wandb/settings
2024-09-06 02:31:16,998 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Loading settings from /app/wandb/settings
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-06 02:31:16,999 WARNING ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Could not save program above cwd: /usr/local/bin/gunicorn
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': None, 'program_abspath': '/usr/local/bin/gunicorn', 'program': '/usr/local/bin/gunicorn'}
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Applying login settings: {'anonymous': 'must'}
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Applying login settings: {'api_key': '***REDACTED***'}
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_setup.py:_flush():77] Applying login settings: {'anonymous': 'must'}
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:_log_setup():524] Logging user logs to /app/wandb/run-20240906_023116-6je98ujt/logs/debug.log
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:_log_setup():525] Logging internal logs to /app/wandb/run-20240906_023116-6je98ujt/logs/debug-internal.log
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:init():608] calling init triggers
2024-09-06 02:31:16,999 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:init():615] wandb.init called with sweep_config: {}
config: {}
2024-09-06 02:31:17,000 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:init():658] starting backend
2024-09-06 02:31:17,000 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:init():662] setting up manager
2024-09-06 02:31:17,002 INFO    ThreadPoolExecutor-0_1:34 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-06 02:31:17,002 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:init():670] backend started and connected
2024-09-06 02:31:17,006 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:init():768] updated telemetry
2024-09-06 02:31:17,006 INFO    ThreadPoolExecutor-0_1:34 [wandb_init.py:init():801] communicating run to backend with 90.0 second timeout
2024-09-06 02:31:53,504 INFO    ThreadPoolExecutor-0_2:34 [wandb_settings.py:_apply_login():1970] Applying login settings: {'anonymous': 'must'}
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Current SDK version is 0.17.9
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Configure stats pid to 34
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Loading settings from /root/.config/wandb/settings
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Loading settings from /app/wandb/settings
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-06 02:31:53,506 WARNING ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Could not save program above cwd: /usr/local/bin/gunicorn
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': None, 'program_abspath': '/usr/local/bin/gunicorn', 'program': '/usr/local/bin/gunicorn'}
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Applying login settings: {'anonymous': 'must'}
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Applying login settings: {'api_key': '***REDACTED***'}
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_setup.py:_flush():77] Applying login settings: {'anonymous': 'must'}
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:_log_setup():524] Logging user logs to /app/wandb/run-20240906_023153-vh16386k/logs/debug.log
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:_log_setup():525] Logging internal logs to /app/wandb/run-20240906_023153-vh16386k/logs/debug-internal.log
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():608] calling init triggers
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():615] wandb.init called with sweep_config: {}
config: {}
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():658] starting backend
2024-09-06 02:31:53,506 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():662] setting up manager
2024-09-06 02:31:53,507 INFO    ThreadPoolExecutor-0_2:34 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-06 02:31:53,507 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():670] backend started and connected
2024-09-06 02:31:53,508 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():768] updated telemetry
2024-09-06 02:31:53,508 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():801] communicating run to backend with 90.0 second timeout
2024-09-06 02:31:55,207 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():852] starting run threads in backend
2024-09-06 02:31:55,347 INFO    ThreadPoolExecutor-0_2:34 [wandb_run.py:_console_start():2465] atexit reg
2024-09-06 02:31:55,348 INFO    ThreadPoolExecutor-0_2:34 [wandb_run.py:_redirect():2311] redirect: wrap_raw
2024-09-06 02:31:55,348 INFO    ThreadPoolExecutor-0_2:34 [wandb_run.py:_redirect():2376] Wrapping output streams.
2024-09-06 02:31:55,348 INFO    ThreadPoolExecutor-0_2:34 [wandb_run.py:_redirect():2401] Redirects installed.
2024-09-06 02:31:55,349 INFO    ThreadPoolExecutor-0_2:34 [wandb_init.py:init():895] run started, returning control to user process
2024-09-06 02:31:55,349 INFO    ThreadPoolExecutor-0_2:34 [wandb_run.py:_config_callback():1392] config_cb None None {'epochs': 5, 'batch_size': 1, 'learning_rate': 1e-05, 'val_percent': 0.1, 'save_checkpoint': True, 'img_scale': 0.5, 'amp': False}
2024-09-06 02:32:46,442 ERROR   ThreadPoolExecutor-0_0:34 [wandb_init.py:init():827] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-06 02:32:46,442 ERROR   ThreadPoolExecutor-0_0:34 [wandb_init.py:init():1239] error in wandb.init()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1229, in init
    return wi.init()
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 833, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-06 02:32:47,054 ERROR   ThreadPoolExecutor-0_1:34 [wandb_init.py:init():827] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-06 02:32:47,054 ERROR   ThreadPoolExecutor-0_1:34 [wandb_init.py:init():1239] error in wandb.init()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1229, in init
    return wi.init()
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 833, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
